apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "echoservice.fullname" . }}
  labels:
    {{- include "echoservice.labels" . | nindent 4 }}
data:
  {{- toYaml .Values.config | nindent 4 }}
