apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "demo-service.fullname" . }}
  labels:
    {{- include "demo-service.labels" . | nindent 4 }}
data:
  {{- toYaml .Values.config | nindent 4 }}
