apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: {{ include "echoservice.fullname" . }}
  labels:
    {{- include "echoservice.labels" . | nindent 4 }}
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts: 
    {{- range $host := .Values.gateway.hosts }}
    - {{ $host }}
    {{- end }}
