apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ include "demo-service.fullname" . }}
  labels:
    {{- include "demo-service.labels" . | nindent 4 }}
spec:
  hosts:
  {{- range $host := .Values.gateway.hosts }}
  - {{ $host }}
  {{- end }}
  gateways:
  - {{ include "demo-service.fullname" . }}
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: {{ include "demo-service.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local
        port:
          number: {{ .Values.service.port }}
